name: Build (Linux)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # nothing here
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Install Necessary Packages
      run: sudo apt update && sudo apt install -y cmake build-essential xorg-dev mesa-common-dev mesa-utils libssl-dev libasound2-dev libpulse-dev libjack-dev

    - name: Install Clang
      if: ${{ matrix.compiler == 'clang' }}
      uses: egor-tensin/setup-clang@v1
      with:
        version: 13
        platform: x64

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ChiraEngine-linux-${{matrix.compiler}}-${{matrix.build_type}}
        path: |
          ${{github.workspace}}/build/resources/
          ${{github.workspace}}/build/ChiraEditor
          ${{github.workspace}}/build/*.s*
